---
version: "3.9"
services:
  web:
    image: tomcat:latest
    depends_on:
      - appdata
    ports:
      - "80:8080"
    volumes:
      - javabin:/usr/java
      - warloc:/usr/local/tomcat/webapps/
  appdata:
    build: ./dockerfiles   
    volumes:
      - javabin:/opt/java/openjdk
      - warloc:/etc/projects/boxfuse-sample-java-war-hello/target  
volumes:
  javabin:
  warloc:
---
