---
version: "3.9"
services:
  web:
    image: tomcat:9.0.20-jre8-alpine
    depends_on:
      - appdata
    ports:
      - "80:8080"
    volumes:
      - warloc:/usr/local/tomcat/webapps:ro
  appdata:
    build: ./dockerfiles   
    volumes:
      - warloc:/etc/projects/boxfuse-sample-java-war-hello/target  
volumes:
  warloc: