---
version: "3.9"
services:
  devjava:
    image: maven:3.8.6-openjdk-11
    #command: mvn clean
    volumes:
      - javabin:/opt/java/openjdk

  web:
    image: tomcat:latest
    depends_on:
      - devjava
    volumes:
      - javabin:/usr/java
volumes:
  javabin:
---
