---
version: "3.9"
services:
  devjava:
    image: maven:3.8.6-openjdk-11
    depends_on:
      - appdata
    command: mvn install
    volumes:
      - javabin:/opt/java/openjdk

  web:
    image: tomcat:latest
    depends_on:
      - devjava
    volumes:
      - javabin:/usr/java
  
  appdata:
    image: ubuntu:20.04
    #command: apt update
    command: 
      - bash-c "apt update && apt install git -y && ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts && git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git"
    volumes:
      - warloc:/etc/project  
volumes:
  javabin:
  warloc:
---
