---
- name: Install tomcat
  hosts: localhost
  become: yes
  
  tasks:
  - name: Install  packages
    apt: name="{{item}}" state=present
    with_items:
      - python3
      - python-pip

  - name: Install pythonSDK
    pip: name="{{item}}" 
    with_items:
      - docker
    vars:
      ansible_python_interpreter: /user/bin/python3

- name: web server configuration
  hosts: prod
  become: yes

  roles:
    - common
    - prod

- name: Application Distribution
  hosts: workbench
  become: yes

  roles:
    - common
    - workbench
