---
# tasks file for workbench
- name: Ensure needed packages presetn
  apt: name="{{item}}" state=present
  with_items:
    - default-jdk
    - maven
    - git

- name: Git pull project
  git: repo="{{git_project_path}}" dest="{{project_folder}}"

- name: Maven compile project
  command: mvn -f "{{project_folder}}"/pom.xml package

- name: Transfer file from workbench to prod
  synchronize: src="{{project_folder}}"/target/*.war dest="{{path_on_prod}}" mode=pull
  delegate_to: 62.84.115.102
  
